### ISSUE TITLE
Start regular releases?

### ISSUE THREAD

**Issue by jbusecke** [zarr-developers/VirtualiZarr#131]
Stuff is moving fast over here (which is awesome!!!), but could we start releasing to pypi?

Happy to set this up as gh action, just wanted to check if there is a reason this is not done yet.

**Comment by TomNicholas** [comment]
The reason is that I wanted to move the repo into the zarr-developers github org first (so that we didn't have to change paths to things after the first release), and I'm waiting for someone from the zarr steering council to do it, see https://github.com/orgs/zarr-developers/discussions/70#discussioncomment-9577781 and https://github.com/TomNicholas/VirtualiZarr/issues/2#issuecomment-2113291550. So help me pressure Ryan to do it!

(Alternatively if we don't think the URL of the repo changing is a huge deal we could just do an initial release now)

**Comment by TomNicholas** [comment]
Up on conda-forge now too FYI https://anaconda.org/conda-forge/virtualizarr
