### ISSUE TITLE
No link to github from the docs

### ISSUE THREAD

**Issue by TomNicholas** [zarr-developers/VirtualiZarr#220]
I can't seem to find any way to get back to this github repo from the docs. I think there should be a github symbol in the top right but there doesn't seem to be.

**Comment by keewis** [comment]
that's because the theme configuration is for `sphinx_book_theme`, but the theme you're using is `pydata_sphinx_theme` (also, the docs link to the old repository, which by now should be your fork):
https://github.com/zarr-developers/VirtualiZarr/blob/fdab54cca8d73af4e44903091e5e00bbeb1bb31c/docs/conf.py#L56-L61

See [`pydata_sphinx_theme`'s page on source buttons](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/source-buttons.html), and [`sphinx_book_theme`'s page on source files](https://sphinx-book-theme.readthedocs.io/en/stable/components/source-files.html).

If you want to keep using `pydata_sphinx_theme`, you'd have to use
```python
html_theme_options = {
    ...
    "github_user": "zarr-developers",
    "github_repo": "VirtualiZarr",
    "github_version": "main",
    "doc_path": "docs",
    ...
}
```
