### ISSUE TITLE
Docs lag the released version

### ISSUE THREAD

**Issue by TomNicholas** [zarr-developers/VirtualiZarr#326]
The last released version of virtualizarr was [v1.1.0](https://github.com/zarr-developers/VirtualiZarr/releases/tag/v1.1.0), but the [releases page of the docs](https://virtualizarr.readthedocs.io/en/stable/releases.html) last mentions v1.0.1, and it mentions that as unreleased.

The docs point to `stable` by default, which is deliberate (to avoid the documentation describing features that aren't yet in a released version), but `stable` seems to be out of date - it should mention `v1.1.0`. It seems `latest` is all as expected, including release notes for `v1.1.0` and the unreleased upcoming version.

Maybe there is something wrong with one of our github actions?

cc @maxrjones

**Comment by maxrjones** [comment]
I think the issue is that the release page wasn't updated when the last release was made - https://github.com/zarr-developers/VirtualiZarr/blob/v1.1.0/docs/releases.rst.

The new notes weren't added until https://github.com/zarr-developers/VirtualiZarr/pull/288. Maybe cut a new patch release and see if it's better?

**Comment by TomNicholas** [comment]
That worked, thanks @maxrjones !
