### ISSUE TITLE
Host our own test files

### ISSUE THREAD

**Issue by maxrjones** [zarr-developers/VirtualiZarr#365]
There have been a couple failing tests for about a week now:
```
FAILED virtualizarr/tests/test_backend.py::TestReadFromURL::test_virtualizarr_vs_local_nisar[HDF5VirtualBackend] - fsspec.exceptions.FSTimeoutError
FAILED virtualizarr/tests/test_backend.py::TestReadFromURL::test_virtualizarr_vs_local_nisar[HDFVirtualBackend] - fsspec.exceptions.FSTimeoutError
```

I'm not yet sure what the cause of these failures are, but they're a bit frustratingly slow to debug because creating a local cache of the file takes a really long time (it's possible this is actually the cause of the failure, based on the timeout error). For example, my regular download speeds are >150 Mbps but the file used in test_virtualizarr_vs_local_nisar downloads at ~.3 MB/s (~2.5 Mbps) (e.g., screenshow below). Unless we implement a persistent local cache in GitHub actions, this will also slow down our CI.  Possibly we could look into signed HTTPS or other mechanisms for faster downloads from ASF, but I'm wondering if we should host our own test files on Open Storage Network or a different cloud provider for more control.

I could apply for an OSN allocation for VirtualiZarr and set it up if it's something we're interested in. Or we'd probably fit in the free limits of cloudfare R2.
<img width="311" alt="Image" src="https://github.com/user-attachments/assets/b400ebd9-40f3-4335-a73b-01a2e792837f" />

**Comment by TomNicholas** [comment]
Wait that test file is 243MB?! No wonder it takes so long. 

Instead of trying to test against such large files we should just concentrate on testing the same features with very tiny specially-made files instead. Then we can store those files in the repo directly, as described in #226.

I think we should close this issue by stopping using this massive NISAR file, as one step towards following the approach in #226.

**Comment by maxrjones** [comment]
Sounds good, let's track over in #226
