### ISSUE TITLE
Write zarr stores with manifest.json files to non-local storage

### ISSUE THREAD

**Issue by TomNicholas** [zarr-developers/VirtualiZarr#46]
Awesome to see this develop, Tom!

Is there a goal of being able to write to non-local storage devices? If so we'd need a different (fsspec?) opener for the context manager?

_Originally posted by @cisaacstern in https://github.com/TomNicholas/VirtualiZarr/pull/45#discussion_r1535907782_

**Comment by TomNicholas** [comment]
@cisaacstern I think now that Icechunk exists this is probably out of date? Or is there still something to do if someone wanted to dump kerchunk references into a bucket?

**Comment by cisaacstern** [comment]
👋 @TomNicholas, I guess it depends if you want these methods 

https://github.com/zarr-developers/VirtualiZarr/blob/7a35bd41d980e1809ba2e6a1777a740ae41d184f/virtualizarr/manifests/manifest.py#L439-L452

to be able to read json from a cloud bucket or any other non-local device.

If so, then I would say this issue is still open. If not, then fine to close!

Not sure if/how the existence of Icechunk relates to this, but at the level of those specific methods it appears to my naive eye as unrelated?

In terms of my own requirements (none), I am personally fine if this is out of scope / `wontfix`.

**Comment by TomNicholas** [comment]
Thanks for the clarification @cisaacstern - I think this can be closed, see https://github.com/zarr-developers/VirtualiZarr/issues/359 for the reasoning.
